"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Transferencia_1 = require("./Transferencia");
const MercadoPago_1 = require("./MercadoPago");
const TarjetaDeCredito_1 = require("./TarjetaDeCredito");
let tarjeta1 = new TarjetaDeCredito_1.TarjetDeCredito(12345678900);
tarjeta1.procesarPago();
tarjeta1.cancelarPago();
tarjeta1.procesarPago();
tarjeta1.generarRecibo();
console.log("----------------------------------------------------");
let mercadopago = new MercadoPago_1.MercadoPago(true, "Compra en supermercado", 6000);
mercadopago.procesarPago();
mercadopago.cancelarPago();
mercadopago.procesarPago();
mercadopago.generarRecibo();
console.log("----------------------------------------------------");
let transferencia = new Transferencia_1.Transferencia("Juan Perez", 20000, "Regalo de cumpleaños");
transferencia.procesarPago();
transferencia.cancelarPago();
transferencia.procesarPago();
transferencia.generarRecibo();
